"""Execution adapters and paper-trading safety gates."""

from .ibkr import (
    IBKRConnectionConfig,
    IBKRContractSpec,
    IBKRMarketSnapshot,
    IBKROrderIntent,
    IBKRPaperBroker,
    IBKRPaperRiskConfig,
    IBKRPaperTradingSession,
    build_nq_future_contract,
    is_paper_tradeable_market_data_type,
    submit_ibkr_paper_order,
)
from .live_signal import LIVE_SIGNAL_COLUMNS, LiveSignalConfig, build_live_signal_row, write_live_signal
from .live_strategy import (
    BEST_MEAN_REVERSION_ALIAS,
    BEST_MEAN_REVERSION_STRATEGY_ID,
    LiveStrategySignalConfig,
    LiveStrategySpec,
    build_strategy_live_signal_row,
    evaluate_mean_reversion_signal,
    evaluate_regime_transition_signal,
    regime_transition_spec,
)
from .agent_gate import (
    AgentGateConfig,
    AgentStrategyGate,
    PaperTradeOutcome,
    build_candidate_trade_context,
    load_strategy_evidence,
    outcome_metrics,
    record_agent_gate_outcome,
)
from .gate_backtest import GateReplayConfig, replay_gate_on_trades
from .paper_report import PaperValidationGateConfig, evaluate_paper_validation_gate, paper_summary_frame, summarize_paper_audits
from .paper_runner import PaperDaemonConfig, PaperRunnerConfig, run_adaptive_portfolio_paper_daemon, run_adaptive_portfolio_paper_once
from .live_paper_trader import LivePaperTraderConfig, LivePaperTraderDaemonConfig, run_live_paper_trader_daemon, run_live_paper_trader_once
from .paper_validation import build_paper_intent_from_trade, load_trade_samples, select_trade_sample
from .tick_recorder import IBKRTickRecorderConfig, record_ibkr_ticks
from .tick_replay import TickReplayDatasetConfig, build_tick_replay_dataset
from .walk_forward import WalkForwardConfig, walk_forward_gate_replay
from .llm_debate_delayed_strategy import (
    DebateDelayedStrategyConfig,
    DebateExecutionPlan,
    FeatureScannerConfig,
    FeatureTrigger,
    LLMDebatePlanner,
    RealtimeDebateTraderConfig,
    RuleDebatePlanner,
    StaticDebatePlanner,
    build_debate_prompt,
    build_intent_from_route,
    invoke_aicode_streaming_json,
    load_tradeable_feature_sets,
    planner_from_env_or_args,
    route_plan,
    run_debate_delayed_scanner_daemon,
    run_debate_delayed_scanner_once,
    run_debate_delayed_strategy_once,
    run_realtime_debate_trader,
    scan_feature_trigger_once,
    select_feature_trigger,
)

__all__ = [
    "IBKRConnectionConfig",
    "IBKRContractSpec",
    "IBKRMarketSnapshot",
    "IBKROrderIntent",
    "IBKRPaperBroker",
    "IBKRPaperRiskConfig",
    "IBKRPaperTradingSession",
    "AgentGateConfig",
    "AgentStrategyGate",
    "GateReplayConfig",
    "WalkForwardConfig",
    "PaperTradeOutcome",
    "PaperValidationGateConfig",
    "PaperRunnerConfig",
    "PaperDaemonConfig",
    "LiveSignalConfig",
    "LivePaperTraderConfig",
    "LivePaperTraderDaemonConfig",
    "IBKRTickRecorderConfig",
    "TickReplayDatasetConfig",
    "LiveStrategySignalConfig",
    "LiveStrategySpec",
    "DebateDelayedStrategyConfig",
    "DebateExecutionPlan",
    "FeatureScannerConfig",
    "FeatureTrigger",
    "LLMDebatePlanner",
    "RealtimeDebateTraderConfig",
    "RuleDebatePlanner",
    "StaticDebatePlanner",
    "BEST_MEAN_REVERSION_ALIAS",
    "BEST_MEAN_REVERSION_STRATEGY_ID",
    "build_nq_future_contract",
    "is_paper_tradeable_market_data_type",
    "build_live_signal_row",
    "build_strategy_live_signal_row",
    "build_candidate_trade_context",
    "build_paper_intent_from_trade",
    "load_trade_samples",
    "load_strategy_evidence",
    "outcome_metrics",
    "select_trade_sample",
    "record_agent_gate_outcome",
    "replay_gate_on_trades",
    "evaluate_paper_validation_gate",
    "summarize_paper_audits",
    "paper_summary_frame",
    "run_adaptive_portfolio_paper_once",
    "run_adaptive_portfolio_paper_daemon",
    "run_live_paper_trader_once",
    "run_live_paper_trader_daemon",
    "record_ibkr_ticks",
    "build_tick_replay_dataset",
    "write_live_signal",
    "build_debate_prompt",
    "build_intent_from_route",
    "invoke_aicode_streaming_json",
    "load_tradeable_feature_sets",
    "planner_from_env_or_args",
    "route_plan",
    "submit_ibkr_paper_order",
    "run_debate_delayed_scanner_daemon",
    "run_debate_delayed_scanner_once",
    "run_debate_delayed_strategy_once",
    "run_realtime_debate_trader",
    "scan_feature_trigger_once",
    "select_feature_trigger",
    "walk_forward_gate_replay",
    "evaluate_mean_reversion_signal",
    "evaluate_regime_transition_signal",
    "regime_transition_spec",
    "LIVE_SIGNAL_COLUMNS",
]
